name: 'lunch-app'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=lunchapp'
      - 'POSTGRES_PASSWORD=secretpassword'
      - 'POSTGRES_USER=appuser'
    ports:
      - '5432:5432'
