spring:
  application:
    name: lunch-app
  datasource:
    url: jdbc:postgresql://localhost:5432/lunchapp
    username: appuser
    password: secretpassword

lunch-app:
  username: pavel
  password: secret
