CREATE TABLE lunch (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date       DATE           NOT NULL,
    meal_price NUMERIC(10, 2) NOT NULL,
    amount_paid NUMERIC(10, 2) NOT NULL
);
